### ISSUE TITLE
Set up SDL2 window and openGL context with config file 

### ISSUE THREAD

**Issue by Bendi11** [Bendi11/OpenGL-DoomClone#1]
# TODO:
- [x] Setup SDL2's window 
- [x] Setup openGL context for SDL2
- [x] Make a config file so settings can be adjusted without needing to recompile 
- [x] Display a simple shape on SDL2 window using openGL
